### ISSUE TITLE
Can't use SSL with latest firmware

### ISSUE THREAD

**Issue by kartben** [loboris/MicroPython_K210_LoBo#21]
My ESP8285 firmware is up-to-date, and I can't seem to use SSL with the latest firmware as the AT firmware crashes. Please see below:

```python
>>> import network, machine, os
>>> wifi = network.wifi
>>> wifi.start(tx=7, rx=6, ssid="***REDACTED***", password="***REDACTED***", wait=True)
True
>>> 
>>> wifi.ifconfig()
('192.168.1.48', '192.168.1.1', '255.255.255.0', '192.168.1.1', '208.67.222.222')
>>> 
>>> wifi.debug(True)
True
>>> 
>>> requests = network.requests
>>> requests.debug(True)
>>> 
>>> res = requests.get('http://loboris.eu/K210/test.txt')
M (6217934) [ATCMD]: AT COMMAND: [AT+CIPSSLSIZE?\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (6231488) [ATCMD]: AT RESPONSE: match condition 1 at position 34 (4 ms, 24 byte(s), buf_start=16)
M (6240285) [ATCMD]: AT COMMAND: [AT+CIPSSLSIZE=16384\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (6253492) [ATCMD]: AT RESPONSE: match condition 1 at position 40 (2 ms, 0 byte(s), buf_start=40)
W (6262357) [WIFI_TASK]: no match, removed [.222.222\r\n^^^^^^+CIPSSLSIZE:40]
M (6269862) [ATCMD]: AT COMMAND: [AT+TCPSTART=0,"TCP","loboris.eu",80,3,0\r\n] Expecting: [0,CONNECT\r\n], [\r\nERROR\r\n], [\r\n+TCPSTART]
M (6325528) [ATCMD]: AT RESPONSE: match condition 1 at position 16 (39 ms, 0 byte(s), buf_start=16)
W (6334334) [WIFI_TASK]: no match, removed [96\r\n^^^^^^^^^^^^^]
M (6340883) [ATCMD]: AT COMMAND: [AT+TCPSEND=0,109\r\n] Expecting: [\r\n>], [\r\n+TCPSEND:Busy\r\n]
M (6353538) [ATCMD]: AT RESPONSE: match condition 1 at position 16 (2 ms, 0 byte(s), buf_start=16)
M (6362234) [ATCMD]: AT COMMAND: [Send data] Expecting: [\r\n+TCPSEND:Complete\r\n], [\r\nOK\r\n], [\r\nERROR\r\n], [FAIL]
W (6373777) [ATCMD]: data: [GET /K210/test.txt HTTP/1.1\x0D\x0AUser-Agent: MicroPython HTTP Client/1.0\x0D\x0AHost: lobo]
M (6432580) [ATCMD]: AT RESPONSE: match condition 1 at position 35 (38 ms, 37 byte(s), buf_start=19)
M (6441482) [WIFI_TASK]: +TCP data request found [+TCP,0,9,1331:]
M (6448038) [WIFI_TASK]: Data for link_id 0 (srv=9), len=1331 [+TCP,0]
M (6455073) [WIFI_TASK]: +TCP Requesting data
M (6575874) [WIFI_TASK]: received (127 ms); socket: len=1331, ovf=0, tail=1331, head=0
Y (6583518) [WIFI_TASK]: Wait for data processing
M (6589110) HTTP_CLIENT: http_on_headers_complete, status=200, offset=269, nread=269
Q (6696708) [WIFI_TASK]: Data processed in 108 ms
M (6701314) [WIFI_TASK]: +TCP Confirm receive
Q (6706711) [WIFI]: Close socket 0 (0)
M (6710617) [ATCMD]: AT COMMAND: [AT+TCPCLOSE=0\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (6724698) [ATCMD]: AT RESPONSE: match condition 1 at position 0 (4 ms, 0 byte(s), buf_start=0)
Y (6733230) [WIFI_TASK]: connection for socket with link_id 0 closed, active=285 ms, time=135 ms
W (6742671) [WIFI_TASK]: closed, removed [0,CLOSED]
Q (6748053) [WIFI_TASK]: Processing delay
>>> res[0]
200
>>> 
>>> res2 = requests.get('https://loboris.eu/K210/test.txt')
M (6769874) [ATCMD]: AT COMMAND: [AT+CIPSSLSIZE?\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (6783728) [ATCMD]: AT RESPONSE: match condition 1 at position 35 (4 ms, 25 byte(s), buf_start=16)
M (6792677) [ATCMD]: AT COMMAND: [AT+TCPSTART=0,"SSL","loboris.eu",443,3,0\r\n] Expecting: [0,CONNECT\r\n], [\r\nERROR\r\n], [\r\n+TCPSTART]
M (7164929) [ATCMD]: AT RESPONSE: match condition 1 at position 41 (355 ms, 0 byte(s), buf_start=41)
Q (7173797) [WIFI_TASK]: Continue
W (7177805) [WIFI_TASK]: no match, removed [^^^^^^^^^^^^^^\r\n+CIPSSLSIZE:16384\r\n^^^^^^^]
Q (7186638) [WIFI_TASK]: more data, check again
M (7191924) [ATCMD]: AT COMMAND: [AT+TCPSEND=0,109\r\n] Expecting: [\r\n>], [\r\n+TCPSEND:Busy\r\n]
M (7205945) [ATCMD]: AT RESPONSE: match condition 1 at position 16 (3 ms, 0 byte(s), buf_start=16)
M (7214641) [ATCMD]: AT COMMAND: [Send data] Expecting: [\r\n+TCPSEND:Complete\r\n], [\r\nOK\r\n], [\r\nERROR\r\n], [FAIL]
W (7226184) [ATCMD]: data: [GET /K210/test.txt HTTP/1.1\x0D\x0AUser-Agent: MicroPython HTTP Client/1.0\x0D\x0AHost: lobo]
W (8249492) [ATCMD]: AT COMMAND: TIMEOUT (1000 ms, 506)
M (8254487) [ATCMD]: AT RESPONSE: no response (506) [\r\n+TCPSEND:109\r\n\r\n ets Jan  8 2013,rst cause:2, boot mode:(3,0)\r\n\r\nload 0x40108000, len 3056, room 16 \r\ntail 0\r\nchksum 0xd7\r\nload 0x3fffb000, len 992, room 8 \r\ntail 8\r\nchksum 0xd7\r\ncsum 0xd7~\r\n==============================\r\nLoBo ESP8266 Bootloader v1.2.0\r\n==============================\r\n   Flash map: 2, 1MB (512+512)\r\n  Flash mode: DOUT, [ESP8285]\r\nReset reason: EXCEPTION (28)\r\n\r\nLoading configured firmware (0)\r\n  Address: 001000\r\nStarting firmware 0, map 2 from 001000...\r\n\r\n\r\nready\r\nWIFI CONNECTED\r\n]
W (8308719) [WIFI_TASK]: no match, removed [^^^^^^^^^^\r\nOK\r\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^]
E (8357942) [WIFI]: Send: error sending data
Q (8362688) [WIFI]: Status: [\r\n+TCPSEND:109\r\n\r\n ets Jan  8 2013,rst cause:2, boot mode:(3,0)\r\n\r\nload 0x40108000, len 3056, room 16 \r\ntail 0\r\nchksum 0xd7\r\nload 0x3fffb000, len 992, room 8 \r\ntail 8\r\nchksum 0xd7\r\ncsum 0xd7~\r\n==============================\r\nLoBo ESP8266 Bootloader v1.2.0\r\n==============================\r\n   Flash map: 2, 1MB (512+512)\r\n  Flash mode: DOUT, [ESP8285]\r\nReset reason: EXCEPTION (28)\r\n\r\nLoading configured firmware (0)\r\n  Address: 001000\r\nStarting firmware 0, map 2 from 001000...\r\n\r\n\r\nready\r\nWIFI CONNECTED\r\n]
E (8414859) TRANS_SSL: Write error, errno=Network is unreachable
E (8421368) HTTP_CLIENT: Error write request
Q (8426147) [WIFI]: Close socket 0 (0)
M (8430584) [ATCMD]: AT COMMAND: [AT+TCPCLOSE=0\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (8444570) [ATCMD]: AT RESPONSE: match condition 2 at position 31 (4 ms, 0 byte(s), buf_start=16)
W (8453289) [WIFI_TASK]: no match, removed [^^^^^^^^^^^^^^^^AT+TCPCL]
W (8514670) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (8575703) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (8587326) [WIFI_TASK]: no match, removed [O]
Q (8591499) [WIFI_TASK]: more data, check again
W (8596718) [WIFI_TASK]: no match, removed [SE=0\r\n^^^^^^]
W (8636708) [WIFI_TASK]: no match, removed [^^^WIFI GOT IP\r\nAT+TCPCL]
W (8697763) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (8758801) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (8819836) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (8880873) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (8941911) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9002943) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9063979) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9125015) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9186050) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9247088) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9308124) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9369165) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9430198) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9491229) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9552268) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9613301) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9674339) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9735377) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9796411) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9857449) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9918488) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (9979525) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (10040559) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (10101592) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (10162631) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (10223665) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (10284704) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (10345738) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
W (10406769) [WIFI_TASK]: no match, removed [OSE=0\r\n^^^^^^^^^AT+TCPCL]
E (10472823) [REQUESTS]: HTTP Request failed: 28675 []
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: HTTP Request failed
>>> res2[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name not defined
>>> 
```

Logs from the ESP UART:
```
==============================
LoBo ESP8266 Bootloader v1.2.0
==============================
   Flash map: 2, 1MB (512+512)
  Flash mode: DOUT, [ESP8285]
Reset reason: EXCEPTION (0)

Loading configured firmware (0)
  Address: 001000
Starting firmware 0, map 2 from 001000...


ready
WIFI DISCONNECT
WIFI CONNECTED
WIFI GOT IP
AT

OK
AT

OK
ATE0

OK
+TCPCOMMANDS:1

OK
+CWMODE:1

OK
+CWJAP:"***REDACTED***","ac:84:***REDACTED***",11,-63,0

OK

OK

OK
+CIPRECVMODE:0

OK

OK

OK
+CIPSNTPCFG:0

OK

OK
+CIPSNTPCFG:1,0,"pool.ntp.org"

OK
+CIPSTA:ip:"192.168.1.48"
+CIPSTA:gateway:"192.168.1.1"
+CIPSTA:netmask:"255.255.255.0"

OK
+CIPDNS_CUR:192.168.1.1
+CIPDNS_CUR:208.67.222.222

OK
+CIPSSLSIZE:4096

OK

OK
0,CONNECT

OK

>
+TCPSEND:109

+TCPSEND:Complete

OK

+TCP,0,9,1331:HTTP/1.1 200 OK
Date: Wed, 19 Feb 2020 17:14:58 GMT
Server: Apache/2.4.29 (Ubuntu)
Last-Modified: Wed, 20 Mar 2019 13:08:43 GMT
ETag: "426-5848652314cc0"
Accept-Ranges: bytes
Content-Length: 1062
Vary: Accept-Encoding
Content-Type: text/plain; charset=UTF-8

===============
Welcome to K210
===============

General Specifications:
-----------------------
 * The K210 includes two 64-bit RISC-V CPU cores, each with a built-in independent FPU.
 * KPU high performance Convolutional Neural Network (CNN) hardware accelerator.
   The primary functions of the K210 are machine vision and hearing,
   which includes the KPU for computing convolutional neural networks and
   an APU for processing microphone array inputs.
 * The K210 features a Fast Fourier Transform (FFT) Accelerator for high performance
   complex FFT calculations. As a result, for most machine learning algorithms,
   the K210 has high-performance processing power.
 * Advanced TSMC 28nm process, temperature range -40°C to 125°C
 * Firmware encryption support
 * Unique programmable IO array maximises design flexibility
 * Low voltage, reduced power consumption compared to other systems
   with the same processing power
 * 3.3V/1.8V dual voltage IO support eliminates need for level shifters

---------
2019 LoBo
---------

OK
0,CLOSED
+CIPSSLSIZE:16384

OK
0,CONNECT

OK

>
+TCPSEND:109

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40108000, len 3056, room 16 
tail 0
chksum 0xd7
load 0x3fffb000, len 992, room 8 
tail 8
chksum 0xd7
csum 0xd7�
==============================
LoBo ESP8266 Bootloader v1.2.0
==============================
   Flash map: 2, 1MB (512+512)
  Flash mode: DOUT, [ESP8285]
Reset reason: EXCEPTION (28)

Loading configured firmware (0)
  Address: 001000
Starting firmware 0, map 2 from 001000...


ready
WIFI CONNECTED
AT+TCPCLOSE=0

ERROR
AT+TCPCLOSE=0

ERROR
AT+TCPCLOSE=0

ERROR
AT+TCPCLOSE=0

ERROR
AT+TCPCLOSE=0

ERROR
AT+TCPCLOSE=0

ERROR
WIFI GOT IP
AT+TCPCLOSE=0

ERROR
AT+TCPCLOSE=0

ERROR
AT+TCPCLOSE=0
```

**Comment by loboris** [comment]
Sorry for late reply.
I can't reproduce this issue. Does it occur every time you try the https request?

Here is my log, I've tried to repeat the request 10 times and had no error.
Maybe you have weak WiFi signal?

In your case ESP8285 crashes with Exception 28 (A load referenced a page mapped with an attribute that does not permit loads).
I've found some references to this exception occuring when WiFi was disconnected and reconnected, but at this time I'm not sure how to fix it.

I'm now working on using ESP32 as WiFi interface, after I'll finish it, I'll try to check the ESP8266 firmware for possible cause of this issue.

```python
>>> res = requests.get('http://loboris.eu/K210/test.txt')
M (141056968) [ATCMD]: AT COMMAND: [AT+CIPSSLSIZE?\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (141070675) [ATCMD]: AT RESPONSE: match condition 1 at position 34 (4 ms, 24 byte(s), buf_start=16)
M (141079639) [ATCMD]: AT COMMAND: [AT+CIPSSLSIZE=16384\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (141092678) [ATCMD]: AT RESPONSE: match condition 1 at position 40 (1 ms, 0 byte(s), buf_start=40)
W (141101689) [WIFI_TASK]: no match, removed [39.121.8\r\n^^^^^^+CIPSSLSIZE:40]
M (141109383) [ATCMD]: AT COMMAND: [AT+TCPSTART=0,"TCP","loboris.eu",80,3,0\r\n] Expecting: [0,CONNECT\r\n], [\r\nERROR\r\n], [\r\n+TCPSTART]
M (141205714) [ATCMD]: AT RESPONSE: match condition 1 at position 16 (79 ms, 0 byte(s), buf_start=16)
W (141214679) [WIFI_TASK]: no match, removed [96\r\n^^^^^^^^^^^^^]
M (141221398) [ATCMD]: AT COMMAND: [AT+TCPSEND=0,109\r\n] Expecting: [\r\n>], [\r\n+TCPSEND:Busy\r\n]
M (141233722) [ATCMD]: AT RESPONSE: match condition 1 at position 16 (1 ms, 0 byte(s), buf_start=16)
M (141242591) [ATCMD]: AT COMMAND: [Send data] Expecting: [\r\n+TCPSEND:Complete\r\n], [\r\nOK\r\n], [\r\nERROR\r\n], [FAIL]
W (141254307) [ATCMD]: data: [GET /K210/test.txt HTTP/1.1\x0D\x0AUser-Agent: MicroPython HTTP Client/1.0\x0D\x0AHost: lobo]
M (141306748) [ATCMD]: AT RESPONSE: match condition 2 at position 35 (31 ms, 22 byte(s), buf_start=19)
M (141315807) [WIFI_TASK]: +TCP data request found [+TCP,0,9,1331:]
M (141322554) [WIFI_TASK]: Data for link_id 0 (srv=9), len=1331 [+TCP,0]
M (141329759) [WIFI_TASK]: +TCP Requesting data
M (141450805) [WIFI_TASK]: received (128 ms); socket: len=1331, ovf=0, tail=1331, head=0
Y (141458621) [WIFI_TASK]: Wait for data processing
M (141464351) HTTP_CLIENT: http_on_headers_complete, status=200, offset=269, nread=269
Q (141571843) [WIFI_TASK]: Data processed in 107 ms
M (141576622) [WIFI_TASK]: +TCP Confirm receive
Q (141582180) [WIFI]: Close socket 0 (0)
M (141586270) [ATCMD]: AT COMMAND: [AT+TCPCLOSE=0\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (141599832) [ATCMD]: AT RESPONSE: match condition 1 at position 0 (3 ms, 0 byte(s), buf_start=0)
Y (141608529) [WIFI_TASK]: connection for socket with link_id 0 closed, active=286 ms, time=136 ms
W (141618151) [WIFI_TASK]: closed, removed [0,CLOSED]
Q (141623707) [WIFI_TASK]: Processing delay
>>> Q (141677855) [WIFI_TASK]: Continue

>>> res[0]
200
>>> res2 = requests.get('https://loboris.eu/K210/test.txt')
M (177172575) [ATCMD]: AT COMMAND: [AT+CIPSSLSIZE?\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (177185807) [ATCMD]: AT RESPONSE: match condition 1 at position 35 (3 ms, 25 byte(s), buf_start=16)
W (177194823) [WIFI_TASK]: no match, removed [^^^^^^^^^^^^^^\r\n+CIPSSLSI]
M (177202169) [ATCMD]: AT COMMAND: [AT+TCPSTART=0,"SSL","loboris.eu",443,3,0\r\n] Expecting: [0,CONNECT\r\n], [\r\nERROR\r\n], [\r\n+TCPSTART]
M (177596935) [ATCMD]: AT RESPONSE: match condition 1 at position 16 (378 ms, 0 byte(s), buf_start=16)
W (177605988) [WIFI_TASK]: no match, removed [ZE:16384\r\n^^^^^^^]
M (177612706) [ATCMD]: AT COMMAND: [AT+TCPSEND=0,109\r\n] Expecting: [\r\n>], [\r\n+TCPSEND:Busy\r\n]
M (177624943) [ATCMD]: AT RESPONSE: match condition 1 at position 16 (1 ms, 0 byte(s), buf_start=16)
M (177633812) [ATCMD]: AT COMMAND: [Send data] Expecting: [\r\n+TCPSEND:Complete\r\n], [\r\nOK\r\n], [\r\nERROR\r\n], [FAIL]
W (177645528) [ATCMD]: data: [GET /K210/test.txt HTTP/1.1\x0D\x0AUser-Agent: MicroPython HTTP Client/1.0\x0D\x0AHost: lobo]
M (177709971) [ATCMD]: AT RESPONSE: match condition 2 at position 35 (43 ms, 22 byte(s), buf_start=19)
W (177719024) [WIFI_TASK]: no match, removed [^^^^^^^^^^\r\nOK\r\n^^^\r\n+TCP]
W (177747794) [WIFI_TASK]: no match, removed [S]
Q (177752139) [WIFI_TASK]: more data, check again
M (177757531) [WIFI_TASK]: +TCP data request found [+TCP,0,9,1331:]
M (177764294) [WIFI_TASK]: Data for link_id 0 (srv=9), len=1331 [+TCP,0]
M (177771498) [WIFI_TASK]: +TCP Requesting data
M (177892556) [WIFI_TASK]: received (128 ms); socket: len=1331, ovf=0, tail=1331, head=0
Y (177900373) [WIFI_TASK]: Wait for data processing
M (177906101) HTTP_CLIENT: http_on_headers_complete, status=200, offset=269, nread=269
Q (178014081) [WIFI_TASK]: Data processed in 109 ms
M (178018860) [WIFI_TASK]: +TCP Confirm receive
Q (178024418) [WIFI]: Close socket 0 (0)
M (178028508) [ATCMD]: AT COMMAND: [AT+TCPCLOSE=0\r\n] Expecting: [\r\nOK\r\n], [\r\nERROR\r\n]
M (178042069) [ATCMD]: AT RESPONSE: match condition 1 at position 0 (4 ms, 0 byte(s), buf_start=0)
>>> Y (178070140) [WIFI_TASK]: connection for socket with link_id 0 closed, active=306 ms, time=136 ms
W (178078998) [WIFI_TASK]: closed, removed [0,CLOSED]
Q (178084554) [WIFI_TASK]: Processing delay
Q (178139098) [WIFI_TASK]: Continue
Q (178142493) [WIFI_TASK]: more data, check again

>>> res2[0]
200
>>> print(res2[2].decode())
===============
Welcome to K210
===============

General Specifications:
-----------------------
 * The K210 includes two 64-bit RISC-V CPU cores, each with a built-in independent FPU.
 * KPU high performance Convolutional Neural Network (CNN) hardware accelerator.
   The primary functions of the K210 are machine vision and hearing,
   which includes the KPU for computing convolutional neural networks and
   an APU for processing microphone array inputs.
 * The K210 features a Fast Fourier Transform (FFT) Accelerator for high performance
   complex FFT calculations. As a result, for most machine learning algorithms,
   the K210 has high-performance processing power.
 * Advanced TSMC 28nm process, temperature range -40°C to 125°C
 * Firmware encryption support
 * Unique programmable IO array maximises design flexibility
 * Low voltage, reduced power consumption compared to other systems
   with the same processing power
 * 3.3V/1.8V dual voltage IO support eliminates need for level shifters

---------
2019 LoBo
---------

>>> 
```

**Comment by kartben** [comment]
Thank you for the feedback, Boris. This may have to do with the ESP8285 indeed. I don't think my Wi-Fi signal is the cause here, but who knows.
I will try to investigate further. In the meantime, if that's OK I suggest we leave this issue open?
